= JAX-RS (REST) Playground project

== Disclaimer
Current source code and version is published without license. +
If you (somebody) want to use this in his project please contact me.
Afterwards I will grant the use of this code without warranty.
When I find some time to inform myself about the different possible licenses at link:http://choosealicense.com[choosealicense.com]
I will probably change to a suitable license.

== General information
This `JAX-RS (REST) Playground` project is just a playground for my personal _JAX-RS (REST)_ samples.


== Technical information
  * The release versions are based on link:http://semver.org[Semantic Versioning 2.0.0].
  * The latest release require `JavaEE 7` (or newer) and is build with link:https://maven.apache.org[Maven] (version `3.3.x`).


== Current Features _(for this branch)_

  * Two JAX-RS endpoints
    ** one very plain `res/messages/...` for testing some _path param options_
    ** one `res/bean/...` for testing with `Bean` responses and according `MessageBodyWriter`
      *** A `MessageBodyWriter` for `Bean`
      *** A `MessageBodyWriter` for `List<Bean>`


== New and Noteworthy

  * *nothing*

== Roadmap

  * *none*
